services:
  postgresql:
    image: postgres:14.9
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: task-prioritizer
    healthcheck:
      test: [ "CMD", "psql", "postgresql://user:password@localhost:5432/task-prioritizer", "-c", "select 1;" ]
      interval: 5s
      timeout: 3s
      retries: 20
